#!/usr/bin/lua
--[[

	Copyright (C) 2022 Tim Wilkinson
	See Contributors file for additional contributors

	This program is free software: you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation version 3 of the License.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License
	along with this program.  If not, see <http://www.gnu.org/licenses/>.

	Additional Terms:

	Additional use restrictions exist on the AREDN(TM) trademark and logo.
		See AREDNLicense.txt for more info.

	Attributions to the AREDN Project must be retained in the source code.
	If importing this code into a new or existing project attribution
	to the AREDN project must be added to the source code.

	You must not misrepresent the origin of the material contained within.

	Modified versions must be modified to attribute to the original source
	and be marked in reasonable ways as differentiate it from the original
	version

--]]

require("iwinfo")
require("aredn.utils")
local json = require("luci.jsonc")

-- read_postdata
local params = nil
if os.getenv("REQUEST_METHOD") == "POST" then
	require('luci.sys')
    require('luci.http')
    local request = luci.http.Request(luci.sys.getenv(),
      function()
        local v = io.read(1024)
        if not v then
            io.close()
        end
        return v
      end
    )
    params = request:formvalue()
end

local f = io.open("/etc/local/lqm.conf")
local config = json.parse(f:read("*a"))
f:close()

if params then
	if tonumber(params.high) then
		config.high = tonumber(params.high)
	end
	if tonumber(params.low) then
		config.low = tonumber(params.low)
	end
	f = io.open("/etc/local/lqm.conf", "w")
	f:write(json.stringify(config, true))
	f:close()
end

local stations = {}
for mac, station in pairs(iwinfo.nl80211.assoclist(get_ifname("wifi")))
do
	if station.signal ~= 0 then
		stations[mac] = {
			snr = station.signal + 95,
			blocked = false
		}
	end
end

for line in io.popen("/usr/sbin/iptables -L input_lqm"):lines()
do
	local mac = line:match("MAC ([0-9A-F:]+)")
	if mac and stations[mac] then
		stations[mac].blocked = true
	end
end

if not (arg and arg[1] == "inline") then
	print "Content-type: application/json\r"
	print "Cache-Control: no-store\r"
	print "\r"
end
print(json.stringify({
	config = config,
	links = stations
}));
