#!/bin/sh

sed -i -e '/|8080|cgi-bin\/lqm/d' /etc/config.mesh/_setup.services.dmz
sed -i -e '/|8080|cgi-bin\/lqm/d' /etc/config.mesh/_setup.services.nat

/usr/sbin/iptables -F input_lqm 2> /dev/null
/usr/sbin/iptables -X input_lqm 2> /dev/null
/usr/sbin/iptables -D INPUT -j input_lqm -m comment --comment 'block low quality links' 2> /dev/null

/usr/local/bin/node-setup -a -p mesh &> /dev/null
/etc/init.d/olsrd restart &> /dev/null
/etc/init.d/manager restart &> /dev/null

exit 0
